INSERT INTO [UserPreferenceValues] ( [UserPreferenceValue], [UserPreferenceType]) 
VALUES	('Anonymous', 'Leaderboard'),
		('HideLeaderboard', 'Leaderboard'),
		('Rank', 'Leaderboard'),
		('Avatar', 'Leaderboard'),
		('Name', 'Leaderboard'),
		('SecurityMaturity', 'Leaderboard'),
		('Points', 'Leaderboard'),
		('Accuracy', 'Leaderboard'),
		('ConfidenceLevel', 'Leaderboard'),
		('TimeSpent', 'Leaderboard'),
		('JoinedDate', 'Leaderboard'),
		('Delta', 'Leaderboard'),
		('IntercomApp', 'Integrations'),
		('UserSnapApp', 'Integrations'),
		('AdminAPIKeyApp', 'API'),
		('UserCommunications', 'Privacy'),
		('Social', 'Privacy'),
		('PublicProfile', 'Privacy'),
		('SecurityMaturity', 'Statistics'),
		('WeeklyCompanyAdmin', 'EmailReports'),
		('MonthlyCompanyAdmin', 'EmailReports'),
		('QuarterlyCompanyAdmin', 'EmailReports'),
		('WeeklyTeamManager', 'EmailReports'),
		('MonthlyTeamManager', 'EmailReports'),
		('QuarterlyTeamManager', 'EmailReports'),
		('RegistrationEmail', 'Communications'),
		('CompanyAdminDefaultRule', 'Sensei'),
		('SenseiFeedback', 'Sensei'),
		('SenseiDataCollection', 'Sensei'),
		('LabAVailability', 'Labs')
;