INSERT INTO [Language] ([LanguageFramework], [LanguageName], [LanguageFrameworkDropdown], [LanguageNameDropdown] )
VALUES	(N'spring', N'java', N'spring', N'java'),
		(N'struts', N'java', N'struts', N'java'),
		(N'ee', N'java', N'ee', N'java'),
		(N'android', N'java', N'android', N'java'),
		(N'express', N'nodejs', N'express', N'nodejs'),
		(N'django', N'python', N'django', N'python'),
		(N'web_forms', N'c_sharp', N'web_forms', N'c_sharp'),
		(N'mvc', N'c_sharp', N'mvc', N'c_sharp'),
		(N'vanilla', N'c_sharp', N'vanilla', N'c_sharp'),
		(N'rails', N'ruby', N'rails', N'ruby'),
		(N'ios', N'objective_c', N'ios', N'objective_c'),
		(N'vanilla', N'swift', N'vanilla', N'swift'),
		(N'symfony', N'php', N'symfony', N'php'),
		(N'vanilla', N'c', N'vanilla', N'c'),
		(N'vanilla', N'cpp', N'vanilla', N'cpp'),
		(N'vanilla', N'plsql', N'vanilla', N'plsql'),
		(N'vanilla', N'kotlin', N'vanilla', N'kotlin'),
		(N'vanilla', N'cobol', N'vanilla', N'cobol'),
		(N'vanilla', N'go', N'vanilla', N'go'),
		(N'angular_io', N'javascript', N'angular_io', N'javascript'),
		(N'react', N'javascript', N'react', N'javascript'),
		(N'play', N'scala', N'play', N'scala'),
		(N'vanilla', N'pseudocode', N'vanilla', N'pseudocode')
;
